version: '3.9'

services:
  database:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
