GET http://localhost:3000/api/user
###
POST http://localhost:3000/api/user
Content-Type: application/json

{
  "name": "John Doe2",
  "email": "john2@gmail.com",
  "password": "John-Doe2",
  "firstName": "John",
  "lastName": "Doe"
}
###
GET http://localhost:3000/api/user/cl7q70y9q0016onagpx7aliv4
###
PUT http://localhost:3000/api/user/cl7q70y9q0016onagpx7aliv4
Content-Type: application/json 

{
  "firstName": "Mark",
  "lastName": "Smith"
}
### 
DELETE http://localhost:3000/api/user/cl7q70y9q0016onagpx7aliv4

